apiVersion: v1
kind: Service
metadata:
  name: developers-live-svc
spec:
  selector:
    app: developers-live
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9002
  type: LoadBalancer
