apiVersion: v1
kind: Service
metadata:
  name: developers-notify-svc
spec:
  selector:
    app: developers-notify
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9003
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: developers-notify-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developers-notify
  template:
    metadata:
      labels:
        app: developers-notify
    spec:
      containers:
        - name: developers-notify
          image: startdreamteam/developers-notify-test:31
