apiVersion: v1
kind: Service
metadata:
  name: developers-member-svc
spec:
  selector:
    app: developers-member
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: developers-member-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developers-member
  template:
    metadata:
      labels:
        app: developers-member
    spec:
      containers:
        - name: developers-member
          image: startdreamteam/developers-member-test:75
          env:
            - name: TZ
              value: Asia/Seoul
